web_redirect_index:
    path: /
    controller: App\Controller\Web\LocaleRedirectController
    defaults:
        route: 'web_index'

web_redirect_old_press:
    path: /presse
    controller: App\Controller\Web\LocaleRedirectController
    defaults:
        route: 'web_press'

web_redirect_old_jobs:
    path: /offene-positionen
    controller: App\Controller\Web\LocaleRedirectController
    defaults:
        route: 'web_jobs'

web_imprint_alias:
    path: /impressum
    controller: App\Controller\Web\LocaleRedirectController
    defaults:
        route: 'web_imprint'

web_privacy_alias:
    path: /datenschutz
    controller: App\Controller\Web\LocaleRedirectController
    defaults:
        route: 'web_privacy'